### ISSUE TITLE
Show the category code next to a tested website

### ISSUE THREAD

**Issue by hellais** [ooni/probe-desktop#11]
We currently don't store the category code of the tested sites.

We should in some way keep track of which category code a website belongs to and show in the results views.

@lorenzoPrimi @xanscale how do you do this inside of the mobile app?

**Comment by lorenzoPrimi** [comment]
We don't. I'm waiting this support from mk, to get the input tested along with the category code. @sbs

**Comment by hellais** [comment]
> We don't. I'm waiting this support from mk, to get the input tested along with the category code

Ok I see.

This is probably something that we should also take into account in the datamodel of the Measurements table. We probably want something like an `ENUM` column to store the category code of a tested URL and populate it with the return value from the callback of MK.

**Comment by lorenzoPrimi** [comment]
the category is already saved in the Measurement table

**Comment by hellais** [comment]
This is now done.
