### ISSUE TITLE
Old build on ooni.org

### ISSUE THREAD

**Issue by Dr-Flay** [ooni/probe-desktop#171]
The build available on the homepage still points to 3.0.2 for Windows and Mac
https://ooni.org/install/all

It would also be advantageous to all users if the site displayed the current version info.

**Comment by hellais** [comment]
Thanks for noticing this!

I have merged the PR which should lead to the updated version being served: https://github.com/ooni/ooni.org/commit/c7d0a1beaffc02455cfe5fb6d913d91243f9bf15.

> It would also be advantageous to all users if the site displayed the current version info.

This is a great suggestion! I filed an issue for it here: https://github.com/ooni/ooni.org/issues/602.
