### ISSUE TITLE
fsevents fails to install as a dependency on Linux

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-desktop#22]
Error log from `yarn install`
> error fsevents@1.2.4: The platform "linux" is incompatible with this module.
> error Found incompatible module

The typical solution seems to be to move `fsevents` under `optionalDependencies` in package.json. e.g [facebook/create-react-app/react-scripts](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L76)

**Comment by hellais** [comment]
I believe we don't depend directly on `fsevents` anymore, so you can probably safely just drop that dependency from the dev dependencies.
