### ISSUE TITLE
Use platform specific paths to load CA certificate

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-desktop#25]
`download-bin.js` tries to use `/etc/ssl/cert.pem` which is seems to be the default location for the darwin platform. Debian uses `/etc/ssl/certs/ca-certificates.crt` while RHEL/Fedora uses another. More about this situation below[1]. I haven't yet checked what Windows uses.

Maybe we should detect the platform and use the corresponding path. This can also help in downloading just the one binary for that platform instead of downloading all available ones.

[1] [An excellent investigation into this matter](https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/)

**Comment by hellais** [comment]
Another approach could be that of fetching `cert.pem` from a known good location on the internet and checking the hash of it.
I think this is probably better also from the perspective of reproducibility of the build.

**Comment by bassosimone** [comment]
Same comment as for #20. I've added reasonable defaults. @sarathms you may want to double check with the link that you provided above; I pulled mine from CURL sources:

https://github.com/measurement-kit/go-measurement-kit/blob/master/internal/systemx/systemx_linux.go#L13

I concur with @hellais that fetching a CA is probably better.

**Comment by sarathms** [comment]
Closing this as we no longer depend on a `cert.pem` for the probe to function.
