### ISSUE TITLE
Unable to open Test Result by clicking the row

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-desktop#26]
Unlike on Windows, the rows representing the test results are not clickable. The only way to open them is by clicking the arrow on the right. There is no highlight on `mouseover` too.

Platform: Linux
Version: 3.0.0-alpha.5

**Comment by hellais** [comment]
Can you try this on the latest version `3.0.0-beta.1`? I have made some changes since alpha.5 that should make the whole row be clickable.

**Comment by sarathms** [comment]
Yes. This is not an issue anymore in `3.0.0-beta.1`. Closing.
