### ISSUE TITLE
 Use corrected name for color fuschia

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-desktop#27]
Change to `fuchsia` in https://github.com/ooni/probe-desktop/blob/master/renderer/components/nettests/performance/index.js#L14

**Comment by camilaavilarinho** [comment]
I'd like to work on this one

**Comment by sarathms** [comment]
Go for it @camilaavilarinho!

If you are interested, there is [this other issue](https://github.com/ooni/explorer/issues/18) which you can do too. Further, fixing these two issues will lead to [closing this one](https://github.com/ooni/design-system/issues/44).
