### ISSUE TITLE
Onboarding: strings are not working properly

### ISSUE THREAD

**Issue by holantonela** [ooni/probe-desktop#29]
**Current**
<img width="1136" alt="Captura de Pantalla 2019-06-06 a la(s) 2 53 27 p  m" src="https://user-images.githubusercontent.com/7602174/59274881-9d308680-8c31-11e9-9703-0305552d2fc4.png">
<img width="1136" alt="Captura de Pantalla 2019-06-06 a la(s) 2 53 21 p  m" src="https://user-images.githubusercontent.com/7602174/59274882-9dc91d00-8c31-11e9-818b-547e4a972f86.png">

**Expected**
https://xd.adobe.com/spec/aa4af2a6-9501-41ed-53ed-d7dd933947b8-dc7b/

**Steps to reproduce**
Install OONI.Probe-3.0.0-beta.3 on MacOS Mojave 10.14

**Comment by hellais** [comment]
What is the system language of your computer?

If you have it set to anything other than english you will see the boilerplate strings as that is useful to aid translators in spotting untranslated strings (the desktop app isn't translated yet, though most of the strings are those of the mobile app).

In the stable production version we are going to make it default to showing the english version if a string is missing in the translation.

**Comment by holantonela** [comment]
> In the stable production version we are going to make it default to showing the english version if a string is missing in the translation.

Great. Should I close this ticket? Or do we rename it to track the default language implementation?

**Comment by hellais** [comment]
This has been fixed in the latest release. It will default to showing strings in English.

Please let us know how it goes!
