### ISSUE TITLE
Implement missing TestResultsDetails views

### ISSUE THREAD

**Issue by hellais** [ooni/probe-desktop#3]
We are currently missing TestResultsDetails views for the following tests:

* [x] Web Connectivity
* [x] Telegram
* [x] NDT
* [x] HTTP Invalid Request Line
* [x] HTTP Header Field Manipulation
* [x] WhatsApp
* [x] Dash

The only one that is implemented is Facebook Messenger and that view can be used as a template to implement the remaining ones. See: https://github.com/ooni/probe-desktop/blob/master/renderer/components/nettests/im/facebook-messenger.js.

**Comment by hellais** [comment]
As we don't have final mockups for these screens yet in OONI Explorer (and the desktop apps should probably share some code there) I am going to suggest we postpone the fully fleshed out views for these to after the beta.

cc @elioqoshi

**Comment by hellais** [comment]
Here are some mocks of these I made:

![Facebook Messenger](https://user-images.githubusercontent.com/424620/64975311-ffdb9300-d8ae-11e9-81af-ec12bb3f12ea.png)
![Web Connectivity Copy 2](https://user-images.githubusercontent.com/424620/64975313-00742980-d8af-11e9-967e-2f01f9f9607a.png)
![Web Connectivity Copy](https://user-images.githubusercontent.com/424620/64975314-00742980-d8af-11e9-9dbe-eec61bec2492.png)


cc @holantonela

**Comment by sarathms** [comment]
Do we want to implement a sticky layout here as was previously planned? The colored `Hero` can be compressed into a bar with some (or all) of the details like status, URL, date, network etc. But I think it would be better to think it through before implementing it.

**Comment by hellais** [comment]
> Do we want to implement a sticky layout here as was previously planned? The colored Hero can be compressed into a bar with some (or all) of the details like status, URL, date, network etc. But I think it would be better to think it through before implementing it.

I think that we must take into account the fact that the top bar needs to stay visible also while you scroll. The cleanest way to do that, I think, would be doing it with a sticky layout.

The code for doing it should already be there.

Would you like me to mockup also how it looks like collapsed?

**Comment by sarathms** [comment]
I don't think a mockup is necessary. The reason I asked is because the sticky feature was part of the older implementation and it wasn't clear if we wanted to move it over into the newer (above) layout.

> `Hero` can be compressed into a bar

I was already referring to the collapsed state here.

**Comment by sarathms** [comment]
This was implemented in these PRs: #44 #49 #53 #57 #58
