### ISSUE TITLE
Inner sections have an empty top nav

### ISSUE THREAD

**Issue by holantonela** [ooni/probe-desktop#30]
**Current**
<img width="1136" alt="Captura de Pantalla 2019-06-06 a la(s) 2 59 24 p  m" src="https://user-images.githubusercontent.com/7602174/59275509-cef61d00-8c32-11e9-8537-e4cf540a2ad8.png">

**Expected**
https://xd.adobe.com/spec/aa4af2a6-9501-41ed-53ed-d7dd933947b8-dc7b/

**Steps to reproduce**
Install OONI.Probe-3.0.0-beta.3 on MacOS Mojave 10.14

**Comment by holantonela** [comment]
Actually, I'm checking the mocks, and it is following the design. It seems very weird to me. @hellais what do you think?

**Comment by hellais** [comment]
We need to have some area on top of the window that the user can grab and drag around. That is why we have that empty div on top.

If we were to remove it then the user would not have a handle to "grab" to move the window.

**Comment by holantonela** [comment]
Mmm, I see where it is coming from. Maybe, should we get close to the standard and use the top section as a nav? If that is the concern, users can drag the app from the left menu.

**Comment by hellais** [comment]
Another option could be to follow the pattern used in the new macOS App Store (which BTW I think has a lot of really good patterns that I think we should be copying):

![AppStoreMacOS](https://user-images.githubusercontent.com/424620/59595669-88069c80-90f6-11e9-8ceb-5f87cb21d0f1.gif)

**Comment by holantonela** [comment]
Yes, that is what I suggested in my previous comment about using it "as a nav." 
We have three different user interface changes happening there:
- The Navigation Bar shows when the user scrolls
- The Navigation Bar is [translucent](https://developer.apple.com/documentation/appkit/nsvisualeffectblendingmode.)
- The Back Button shows when the user reaches the second level of navigation. It means [that the back arrow living at the left panel](https://user-images.githubusercontent.com/7602174/59617662-20078480-90fd-11e9-806c-d5ddcc682d3f.png) should be removed and relocated at the Navigation Bar

Is it doable at this stage?

**Comment by hellais** [comment]
This has been fixed in the latest release. Check it out!

Closing.
