### ISSUE TITLE
Fix translations

### ISSUE THREAD

**Issue by MarisKori** [ooni/probe-desktop#36]
What is this? Expected to see at least English.
![image](https://user-images.githubusercontent.com/18173966/61990841-78149d80-b050-11e9-9a00-a186c8f5c4e5.png)
OONI.Probe.Setup.3.0.0-beta.3.exe, Windows 7 x64

**Comment by sarathms** [comment]
These are keys for the localisation library to translate to whichever language (incl. English) the user wants to see. Either the build didn't bundle the default English translations at all or there is some other bug. Thanks for reporting :+1:

**Comment by Czechball** [comment]
Same problem - ooniprobe-desktop-setup-3.0.0-beta.4.exe - Windows 10 64 Version 1903, build 18362.329

**Comment by hellais** [comment]
This should be fixed in the latest release candidates.

Please let us know if it works for you and thanks for testing OONI Probe!
