### ISSUE TITLE
Fix Hero background colors in measurment screens

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-desktop#55]
The Hero component seems to render in unexpected ways. It looks like it renders two semi-transparent elements with different dimensions on top of each other like in this screenshot.

![Screenshot from 2019-10-11 16-23-39](https://user-images.githubusercontent.com/700829/66682585-86338c80-ec43-11e9-8004-6006af0cc54c.png)

**Comment by hellais** [comment]
This is no longer a problem.
