### ISSUE TITLE
Finish the measurement pages

### ISSUE THREAD

**Issue by hellais** [ooni/probe-desktop#66]
Currently several bits are missing from the measurement page:
* [x] Methodology link should point to the nettest pages on our website and use a styled button
* [x] Raw Data should open the raw data and use a styled button
* [x] Explorer URL should point to the explorer address for the measurement (the format of this is `https://explorer.ooni.org/$REPORT_ID?input=$INPUT`) and it should be omitted if the result is not uploaded
* [x] Remove the view log button as I don't think we have support for logs

**Comment by hellais** [comment]
This is actually a duplicate of: https://github.com/ooni/probe-desktop/issues/55.

**Comment by sarathms** [comment]
This was merged into `master` via #74
