### ISSUE TITLE
Style the Running test view based on the mockups

### ISSUE THREAD

**Issue by hellais** [ooni/probe-desktop#9]
See: https://xd.adobe.com/spec/aa4af2a6-9501-41ed-53ed-d7dd933947b8-dc7b/

**Comment by hellais** [comment]
This is done inside of: https://github.com/ooni/probe-desktop/pull/18

**Comment by sarathms** [comment]
Is there anything left to be done on this one?

**Comment by hellais** [comment]
I would say this is complete. We can close this issue.
